name: gendara
channels:
  - conda-forge
dependencies:
  - pandas
  - python=3.12
  - librosa
  - pytorch
  - pytorch-lightning
  - ipykernel
  - wandb
  - resampy
  - pip:
      - torchlibrosa==0.1.0
